### PR TITLE
helper/hashitools: ignore stderr when checking version

### LINKED ISSUE #70: Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31:
Tried to install on a almost clean OSX 10.10.5. Used brew cask to install Virtualbox, otto tried pulling in vagrant but it seemed to fail, so I used brew cask to pull in vagrant (this might have left me with a half-broken version somewhere). Trying `otto dev` on the `otto-getting-started` dir gives me 

`Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31:`

Running vagrant by itself spits out the usual help text - doesn't seem broken.

### PR DESCRIPTION
**Pull request by phinze**
fixes #70

I did a quick sweep of all our tools, and they all print version to
stdout, so ignoring stderr should be AOK.

### CODE REVIEW

File: helper/hashitools/project_test.go [hunk 1]
```diff
@@ -21,6 +22,41 @@ func TestProjectLatestVersion(t *testing.T) {
...
+
+func (t *stubInstaller) InstallAsk(installed, required, latest *version.Version) (bool, error) {
+	return false, nil
+}
+func (t *stubInstaller) Install(*version.Version) error { return nil }
+func (t *stubInstaller) Path() string                   { return t.path }
+
+// https://github.com/hashicorp/otto/issues/70
+func TestVersion_vagrantStdErrWarning(t *testing.T) {
+	path, err := filepath.Abs(filepath.Join(
```
Comment (mitchellh) [inline helper/hashitools/project_test.go]: We need a `if runtime.GOOS != "windows"` on this one.

**Comment by mitchellh** [comment]
One issue with the test then GLTM

**Comment by mitchellh** [comment]
LGTM*

File: helper/hashitools/project_test.go (hunk 1 above)
Comment (phinze) [inline helper/hashitools/project_test.go]: Is this because of the `./` below? Is there a simple way to just make it work properly instead?

Maybe `filepath.Abs(filepath.Join(".", "test-fixtures", ...)` ?

Comment (mitchellh) [inline helper/hashitools/project_test.go]: No this is because we execute a shell script to get the version, so we assume a shell and `echo` and such. :)

Comment (phinze) [inline helper/hashitools/project_test.go]: Oh. lol. yes.
